name: Setup OpenLiberty on AKS

on:
  workflow_dispatch:
    inputs:
      disambiguationSuffix:
        description: 'Included in names to disambiguate. Get from another pipeline execution'
        required: true
  repository_dispatch:

env:
    refArmttk: d97aa57d259e2fc8562e11501b1cf902265129d9
    refJavaee: 85d5d10dd045a90452ae01cad20b258ce853ec18
    azCliVersion: 2.30.0
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    location: eastus
    resourceGroupForOpenLibertyAks: ol-aks-${{ github.event.inputs.disambiguationSuffix }}-${{ github.run_number }}
    userAssignedManagedIdentity: ${{ secrets.USER_ASSIGNED_MANAGED_IDENTITY_ID }}
    aksRepoUserName: WASdev
    aksRepoBranchName: 3f57f29d36538edd03b4ed3c854d523cc009b0af

jobs:
    preflight:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout azure-javaee-iaas
          uses: actions/checkout@v2
          with:
            repository: Azure/azure-javaee-iaas
            path: azure-javaee-iaas
            ref: ${{ env.refJavaee }}
        - name: Checkout arm-ttk
          uses: actions/checkout@v2
          with:
            repository: Azure/arm-ttk
            path: arm-ttk
            ref: ${{ env.refArmttk }}
        - name: Checkout ${{ env.aksRepoUserName }}/azure.liberty.aks
          uses: actions/checkout@v2
          with:
            repository: ${{ env.aksRepoUserName }}/azure.liberty.aks
            path: azure.liberty.aks
            ref: ${{ env.aksRepoBranchName }}
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build azure-javaee-iaas
          run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml

        - name: Build and test ${{ env.aksRepoUserName }}/azure.liberty.aks
          run: |
            cd azure.liberty.aks
            mvn -Ptemplate-validation-tests clean install
        - name: Generate artifact file name and path
          id: artifact_file
          run: |
            version=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' azure.liberty.aks/pom.xml)
            artifactName=azure.liberty.aks-$version-arm-assembly
            unzip azure.liberty.aks/target/$artifactName.zip -d azure.liberty.aks/target/$artifactName
            echo "##[set-output name=artifactName;]${artifactName}"
            echo "##[set-output name=artifactPath;]azure.liberty.aks/target/$artifactName"
        - name: Archive azure.liberty.aks template
          uses: actions/upload-artifact@v1
          if: success()
          with:
            name: ${{steps.artifact_file.outputs.artifactName}}
            path: ${{steps.artifact_file.outputs.artifactPath}}
             
    deploy-openliberty-on-aks:
        needs: preflight
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ${{ env.aksRepoUserName }}/azure.liberty.aks
              uses: actions/checkout@v2
              with:
                repository: ${{ env.aksRepoUserName }}/azure.liberty.aks
                path: azure.liberty.aks
                ref: ${{ env.aksRepoBranchName }}
            - name: Get version information from azure.liberty.aks/pom.xml
              id: version
              run: |
                version=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' azure.liberty.aks/pom.xml)
                echo "version=${version}" >> $GITHUB_ENV
            - name: Output artifact name for Download action
              id: artifact_file
              run: |
                artifactName=azure.liberty.aks-$version-arm-assembly
                echo "artifactName=${artifactName}" >> $GITHUB_ENV
                echo "##[set-output name=artifactName;]${artifactName}"
            - name: Download artifact for deployment
              uses: actions/download-artifact@v1
              with:
                name: ${{steps.artifact_file.outputs.artifactName}}
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Create Resource Group
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    echo "create resource group" ${{ env.resourceGroupForOpenLibertyAks }}
                    az group create --verbose --name ${{ env.resourceGroupForOpenLibertyAks }} --location ${{ env.location }}
            - name: Checkout cargotracker
              uses: actions/checkout@v2
              with:
                path: cargotracker
            - name: Prepare parameter file
              run: |
                echo "replace placeholders using real parameter"
                sed -i "s/#location#/${location}/g; \
                        s/#userAssignedManagedIdentity#/${userAssignedManagedIdentity}/g; \
                        s/#testbranchName#/${aksRepoBranchName}/g; \
                        s/#gitUserName#/${aksRepoUserName}/g" \
                        cargotracker/cargotracker-liberty/src/test/aks/parameters.json
            - name: Archive parameters.json
              uses: actions/upload-artifact@v1
              with:
                name: archivefiles
                path: cargotracker/cargotracker-liberty/src/test/aks/parameters.json
            - name: Validate Deploy of WebLogic Server Cluster Domain offer
              id: validate-openliberty-cluster-deployment
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az deployment group validate \
                    --debug \
                    --resource-group ${{ env.resourceGroupForOpenLibertyAks }} \
                    --name openliberty-on-aks \
                    --parameters @cargotracker/cargotracker-liberty/src/test/aks/parameters.json \
                    --template-file ${artifactName}/mainTemplate.json
            - name: Deploy WebLogic Server Cluster Domain offer
              id: deploy-openliberty-cluster
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az deployment group create \
                    --verbose \
                    --resource-group ${{ env.resourceGroupForOpenLibertyAks }} \
                    --name openliberty-on-aks \
                    --parameters @cargotracker/cargotracker-liberty/src/test/aks/parameters.json \
                    --template-file ${artifactName}/mainTemplate.json
